apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-rclone-admin-transfers
  namespace: dts-dmo-admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: sa-rclone-user-transfers
 namespace: dts-dmo-user