runtime: nodejs20
entrypoint: npm run start
service_account: sa-app-dts-ui@dmo-test-higashi.iam.gserviceaccount.com #TODO: STEP 4
vpc_access_connector:
  name: projects/dmo-test-higashi/locations/us-central1/connectors/dts-serverless-vpc #TODO: STEP 4
  egress_setting: all-traffic